### ISSUE TITLE
IntelliJ click and scroll selection issue

### ISSUE THREAD

**Issue by simonrob** [folivoraAI/BetterTouchTool#2198] opened 2018-03-08 12:50 UTC
#### Description of bug/feature request/question:
Using a Magic Mouse and IntelliJ / Android Studio, making a text selection that ends with the pointer outside of the text view usually (though not always) results in text selection not ending. This means that when you next scroll, text selection continues. See the video below, which better explains the issue.

![btt-bug](https://user-images.githubusercontent.com/934006/37151734-b357be7e-22ce-11e8-9f12-224e0a012428.gif)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Magic Mouse

#### Device information:

Type of Mac: Macbook Pro
macOS version: 10.12.6
BetterTouchTool version: Both the latest release, and latest alpha (2.360)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
Might be related to #1371 / #1388? Disabling BetterTouchTool for Android Studio fixes this issue.

**Comment by fifafu** [comment] 2018-03-08 12:54
Unfortunately IntelliJ doesn't play nicely with apps that use the CGEventTap API in macOS.

Does this only happen with the Magic Mouse or also with the Trackpad?

**Comment by simonrob** [comment] 2018-03-08 13:14
I thought it was only the Magic Mouse, but actually, it turns out that it happens with the trackpad as well.

This is a fairly recent issue - I've used both BetterTouchTool and IntelliJ for years, but have only noticed this problem in the past few months.

**Comment by mndholder** [comment] 2018-03-08 14:20
I reported the same issue here (although probably worded it poorly):
https://github.com/fifafu/BetterTouchTool/issues/2194
I confirm that it happens with trackpad as well.

**Comment by fifafu** [comment] 2018-03-10 23:16
Could  one of you try whether running this terminal command while BTT is quit changes anything?

```defaults write com.hegenberg.BetterTouchTool BTTProblematicEventTapApps -array 'com.google.android.studio'````

(This would be for android studio, for intellij you'd need to adapt the bundle identifier)

**Comment by mndholder** [comment] 2018-03-11 12:12
My searchbox issue is still reproducible after running this command (I am using Webstorm):

```
defaults write com.hegenberg.BetterTouchTool BTTProblematicEventTapApps -array 'com.jetbrains.WebStorm'
```

Also tried restarting BTT and Webstorm just in case

**Comment by fifafu** [comment] 2018-03-11 19:05
Are you running the latest version of Webstorm?
Maybe also try updating to the new BTT alpha, although I think there hasn't been a change in that area.

At the moment I'm unable to reproduce the issue on my machine :-(

Tha'ts the one I used for testing:
![image](https://user-images.githubusercontent.com/8820811/37257273-76b164f2-2567-11e8-8561-9f45e66b5860.png)

**Comment by mndholder** [comment] 2018-03-11 19:56
I was using `v2017.3.2`. Updated it to the latest one, but no luck :(

The issue is very easy to reproduce on my machine for some reason. It takes something like 5 attempts to get the following:
![screencast 2018-03-11 22-37-44](https://user-images.githubusercontent.com/8880741/37257655-86e258ac-257d-11e8-993f-8780b3913b22.gif)

Very strange, considering that I haven't touched any settings (basically using BTT for window snapping  feature only).

Please tell if there's anything else I can do to help to narrow down the issue. It is very annoying, but I don't want to stop using BTT :)

**Comment by fifafu** [comment] 2018-03-11 20:20
I think this will probably be need to fixed in intellij, something is strange with their event handling in regards to CGEventTaps.
I have added some workarounds in previous versions of BTT, but they don't seem to work anymore (at least on your machines)

I'll do some more testing soon. FOr now disabling BTT for webstorm/intellij should workaround the issue.

**Comment by simonrob** [comment] 2018-03-12 10:39
The BTTProblematicEventTapApps setting seems to have fixed the problem for me with Android Studio 3.0.1 and BetterTouchTool 2.360. Thanks!

**Comment by fifafu** [comment] 2018-03-12 10:54
@mndholder  was BTT quit when you executed that command? (that's important otherwise it will be overridden again)

Does ```defaults read com.hegenberg.BetterTouchTool BTTProblematicEventTapApps``` show webstorm?

@simonrob nice! Let's see if it stays like that.

**Comment by mndholder** [comment] 2018-03-14 10:34
>was BTT quit when you executed that command?
No. But I checked the default and if it stays there after I restarted BTT and Webstorm.

The command shows what I added:
```
$ defaults read com.hegenberg.BetterTouchTool BTTProblematicEventTapApps
(
    "com.jetbrains.WebStorm"
)
```

**Comment by simonrob** [comment] 2018-05-21 10:44
Just to add to this while it is still open:

- Find the package name with, e.g.: `mdls -name kMDItemCFBundleIdentifier -r /Applications/IntelliJ\ IDEA\ CE.app/`
- Use `-array-add` rather than just `-array` if you're using multiple apps that have this problem (e.g., IntelliJ Idea, Android Studio) so that you're not just replacing the list each time: `defaults write com.hegenberg.BetterTouchTool BTTProblematicEventTapApps -array-add 'com.jetbrains.intellij.ce'`

**Closed** 2018-11-08 11:44 UTC
