### ISSUE TITLE
BTT created Touchbar keys can't be used in combination with key modifiers.

### ISSUE THREAD

**Issue by jredwards** [folivoraAI/BetterTouchTool#992] opened 2017-05-25 20:13 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Touchbar keys can't be used in combination with key modifiers.

e.g. If I map a touchbar button to F7, I cannot use an Alt-F7 hotkey combo with that touchbar key. They only work as standalone keys.

Note that this is generally possible (if I hold fn to get to the F keys, the combo will work), it just doesn't appear to be possible with keys created by BTT. My specific use case was that I wanted a handful of F keys to be showing in a particular application all the time, but did not want to force the application to show F keys instead of the touch bar the whole time.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar

#### Device information:

Type of MacBook Pro 15 inch 2016
macOS version: 10.12.5
BetterTouchTool version: 2.12 (631)

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

The workaround is to build a button for each full key combo you want (you could even group them if you were so inclined). This is nice for having a single button for each function, but not as extensible.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by oleg-malakhov** [comment] 2017-10-24 15:08
+1 for this too.

I wanted to create my own panel with functional and custom buttons for some applications, but I can't use them, because I need combinations like "⌘ + F12" or "⇧ + F6" that don't work with BTT created buttons (but work fine with the system ones).
The application I was going to use them with is IntelliJ Idea.

**Comment by lennartcl** [comment] 2017-10-30 08:58
+1

also, this appears to be a duplicate of https://github.com/fifafu/BetterTouchTool/issues/236 (but I'll use the opportunity to +1 twice when I get it!)

**Comment by norbertstoll** [comment] 2018-10-12 07:59
I'll do it like @lennartcl... +1 here and in #236

**Closed** 2018-11-08 11:47 UTC

**Comment by peterclary** [comment] 2018-12-18 21:55
+1

So #236 has been closed because it's a duplicate of this one, and this one has been closed because it's a duplicate of #236?

**Comment by fifafu** [comment] 2018-12-18 21:57
BTT has switched to community.folivora.ai for issue tracking early this year. This issue tracker is only still up for reference, in case you still need help with this feature/bug/question, please post again on https://community.folivora.ai.
