### ISSUE TITLE
Windows moving when reactivated with normal mouse

### ISSUE THREAD

**Issue by abertheham** [folivoraAI/BetterTouchTool#1038] opened 2017-06-04 17:38 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:
Windows moving upon reactivation. It's just slightly up and to the left, but enough to be noticeable and disruptive to my work flow (I've set up a snap area so that if I can put any window there and take a screenshot of it using a specific screen-rectangle preset (easier than a multistep process like {screenshot-->window capture mode-->move mouse-->click-->return mouse}).
Notes:
- Only occurs with normal mice (I've tried several).
- Only happens with initial reactivation of the window.  Once it's active, subsequent clicks do not move it.
- Is not due to mouse movement or sensitivity or anything like that.  It even happens with a mouse that has no ability to track movement (I physically removed the optics entirely and use it as a clicker for said screenshots).
- Only happens if windows are clicked somewhere that they can be dragged (i.e. on the titlebar - or in the case of VLC, anywhere in the video window).
- Occurs on Mouse-up, not down.  
- Click duration doesn't seem to matter.
- Happens after dragging too (i.e. when the window is dropped, it still moves just a little bit).

[See this video for demonstration of the problem.](https://youtu.be/wGvw5NAbmL0)

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Normal mouse

#### Device information:

Type of Mac: MBP 13 Non-Retina, Mid 2012
macOS version: macOS Sierra 10.12.5
BetterTouchTool version:  2.20

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):
 
Issue is "resolved" by disabling/quitting BTT (out of the question) but not by restarting it.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

Have gone through all the normal first-steps (and several others) but the problem persists.

**Comment by abertheham** [comment] 2017-06-05 12:47
Edit:  Since posting this, I've noticed the same thing happening using my MagicTrackpad (original), also.  Not with anywhere near the same regularity - it has only happened once or twice with the trackpad, but happens literally every time with my mouse.

**Comment by abertheham** [comment] 2017-06-18 21:58
Anyone else experiencing this?  Any thoughts on things to try or hypotheses on what's causing the problem would be much appreciated.

It's been like an itch that I just barely can't reach for the last couple weeks...

**Comment by paulmoons** [comment] 2017-06-27 13:10
Yes, I have just posted this: https://github.com/fifafu/BetterTouchTool/issues/1128 which now that I have read your entry, looks like its a dupe of your problem. I thought they were moving up and to the left but tonight the windows moved up only. Weird!

**Comment by fifafu** [comment] 2017-06-27 21:09
Unfortunately I can't seem to reproduce this on my machines.
It would be great if you could open the "About" tab in BTT and click the "Export Debug Info" button (best try to reproduce the issue before doing that, so it may be in the logs).

This will create a folder "BetterTouchToolDebug" on your Desktop, please send that with reference to this issue to me via boastr.net@gmail.com

**Comment by paulmoons** [comment] 2017-06-27 23:57
Debug info sent. :)

**Comment by paulmoons** [comment] 2017-07-10 00:55
Bug persists in v2.266. Also, the direction of the one pixel creep seems to change from time to time. Sometimes it is left other times it is up and other times it is up and to the left. Right now for example I have a window that has has hit the top menu bar but continues to creep to the left one pixel on each click. 

I'm not 100% sure but I think this has something to do with having windows snapped with padding around them. Are your windows set to snap hard up against the edge @abertheham or with padding?

**Closed** 2018-11-08 11:47 UTC
