### ISSUE TITLE
Per tab profiles or mappings (e.g. in Chrome)

### ISSUE THREAD

**Issue by rafenden** [folivoraAI/BetterTouchTool#657] opened 2017-03-12 22:57 UTC
#### Description of feature request:
It would be super cool if I could add tab-related apps (profiles) to the BTT.
I would like to remap some of the keys when I visit specific websites in Chrome; this could be possible by detecting the window title.

I would remap my mouse buttons in Gmail. Currently, my left and the right scroll wheel are used as arrow keys, but they could be used to go to the previous and next email since Gmail supports shortcuts. I am pretty sure there would be more apps that could take advantage of this new functionality.

Please consider it.

**Comment by cleverjackal** [comment] 2017-03-13 16:19
BTT based on specific criteria (not just current application, but application window title or even window class) is a very nice idea. AutoHotKey on Windows allows much flexibility for such options. However, AutoHotKey is much different in that it is a scripting language with which one can make scripts. BTT is more GUI-based. I don't know if the (sole) developer is interested in adding this (little requested) feature in, when there are so many other features that users want added. Don't get me wrong, I think it's a great idea that BTT would benefit from. However, the developer has limited time (as do we all) so unless this is something easy to implement (which he should be able to tell), he's not going to bother adding it in, in my opinion (as the demand is very low).

**Comment by rafalenden** [comment] 2017-03-13 16:22
In the Web apps era this seems to be a future-proof functionality.

**Comment by fifafu** [comment] 2017-03-24 13:31
I'm working on something like this - however it's not that easy because BTT can not easily be notified when e.g. the tab of a window changes. 

 Hope to have something ready soon.

**Comment by cleverjackal** [comment] 2017-03-24 19:20
That sounds really cool, thanks. I wish Apple made it a bit easier to work in the system, but sometimes security comes with certain trade-offs.

**Comment by cornelius1** [comment] 2017-05-27 18:48
Isn't this a duplicate of issue #49, too?

Also, any updates on when this feature might be ready? ^_^

**Closed** 2018-11-08 11:49 UTC
Labels: feature request
