### ISSUE TITLE
Windows Snapping stop working until I "Restart BetterTouchTool"

### ISSUE THREAD

**Issue by story1234** [folivoraAI/BetterTouchTool#1888] opened 2017-12-16 19:37 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Description of bug/feature request/question:

Windows Snapping would not activate/work after a while.  I had to manually restart BetterTouchTool and it works again.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):

Macbook Trackpad

#### Device information:

Type of Mac: Macbook Pro 15" Retina 2013 Late
macOS version: 10.12.6
BetterTouchTool version: 2.318

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by fifafu** [comment] 2017-12-17 14:25
Has this only happened once or multiple times?

**Comment by fifafu** [comment] 2017-12-17 17:58
Can you see any pattern? (e.g. after using a specific application?)

**Comment by story1234** [comment] 2017-12-17 18:06
Nope.
  
Just regular browsing.
  
Keyboard short cut works, just not mouse drag to edge of screen.     It works right away after I click "restart better touch tool"
  

  
  

  
  
>

**Comment by lauer** [comment] 2017-12-18 08:51
Seen the same problem here - I will also try to look for a pattern

**Comment by tomislav** [comment] 2017-12-19 15:46
I have the same issue. I use my MBP 2016 in clamshell mode with a LG Ultrafine 5K display attached, if it matters.

**Comment by fifafu** [comment] 2017-12-19 16:10
If you notice it stopped working, please go to to the about tab in BetterTouchTool and click the "export debug information" button. This will create a folder called BetterTouchToolDebug on your desktop. If possible please send that folder to me (boastr.net@gmail.com)

**Comment by tomislav** [comment] 2017-12-20 18:17
I sent you an email with the debug files.

I also included a “working” folder with debug information I made after I restarted Bettertouchtool and snapping was working again.

**Comment by nienkeboomsma** [comment] 2018-01-04 14:54
I have also been experiencing this for quite a while. I'll start collecting debug information too.

**Comment by goirle** [comment] 2018-01-06 15:07
Any update on this issue?

**Comment by fifafu** [comment] 2018-01-06 15:59
Unfortunately I haven't been able to reproduce it yet (although I have received debug infos from 3 users)

Seems to be something specific to some machines but I have not been able to figure it out yet.

:-(

**Comment by goirle** [comment] 2018-01-06 19:51
Thanks,
I am using High Sierra, could that have coused the problem?


----- Bericht beantwoorden -----
Van: "Andreas Hegenberg" <notifications@github.com>
Aan: "fifafu/BetterTouchTool" <BetterTouchTool@noreply.github.com>
CC: "goirle" <adenjosien@hotmail.com>, "Comment" <comment@noreply.github.com>
Onderwerp: [fifafu/BetterTouchTool] Windows Snapping stop working until I "Restart BetterTouchTool" (#1888)
Datum: za, jan. 6, 2018 16:59


Unfortunately I haven't been able to reproduce it yet (although I have received debug infos from 3 users)

Seems to be something specific to some machines but I have not been able to figure it out yet.

:-(

**Comment by nienkeboomsma** [comment] 2018-01-06 20:39
I had these issues on Sierra as well. Now I'm on High Sierra and they persist.

**Comment by goirle** [comment] 2018-01-11 10:27
I am using BettertouchTool primarily for snapping, now I have just noticed that “BetterSnapTool” is available in the App store.
Is this the same app or could I give that app a go to see if the same problem occurs?

Using the current version of BTT gives me too much problems, if it’s functional it’s a great app but for now doesn’t live up to my expectations.

Hope you will be able too provide a fix for this soon, otherwise I will delete the app and go back to “magnet”









Op 6 jan. 2018, om 20:50 heeft adenjosien@hotmail.com<mailto:adenjosien@hotmail.com> het volgende geschreven:



Thanks,
I am using High Sierra, could that have coused the problem?


----- Bericht beantwoorden -----
Van: "Andreas Hegenberg" <notifications@github.com<mailto:notifications@github.com>>
Aan: "fifafu/BetterTouchTool" <BetterTouchTool@noreply.github.com<mailto:BetterTouchTool@noreply.github.com>>
CC: "goirle" <adenjosien@hotmail.com<mailto:adenjosien@hotmail.com>>, "Comment" <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Onderwerp: [fifafu/BetterTouchTool] Windows Snapping stop working until I "Restart BetterTouchTool" (#1888)
Datum: za, jan. 6, 2018 16:59


Unfortunately I haven't been able to reproduce it yet (although I have received debug infos from 3 users)

Seems to be something specific to some machines but I have not been able to figure it out yet.

:-(

**Comment by fifafu** [comment] 2018-01-11 10:37
Bettersnaptool is using the same code as BetterTouchTool for the snapping, so there should be the same issue. 
However I have not yet received any bugreports for BetterSnapTool (but given that only a handful of users seem to encounter this with BetterTouchTool, it may just be luck that nobody has encountered it in Bettersnaptool yet)

**Comment by goirle** [comment] 2018-01-11 10:44
Thanks,

Can I try BST please, just to make sure that this error is related to BTT only?



Op 11 jan. 2018, om 11:37 heeft Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Bettersnaptool is using the same code as BetterTouchTool for the snapping, so there should be the same issue.
However I have not yet received any bugreports for BetterSnapTool (but given that only a handful of users seem to encounter this with BetterTouchTool, it may just be luck that nobody has encountered it in Bettersnaptool yet)

**Comment by goirle** [comment] 2018-01-12 08:03
I don’t expect the problem being solved and I did not received any response on my request to use BST for testing purposes.

So I will take my loss and remove BTT from my iMac.


Op 11 jan. 2018, om 11:37 heeft Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Bettersnaptool is using the same code as BetterTouchTool for the snapping, so there should be the same issue.
However I have not yet received any bugreports for BetterSnapTool (but given that only a handful of users seem to encounter this with BetterTouchTool, it may just be luck that nobody has encountered it in Bettersnaptool yet)

**Comment by fifafu** [comment] 2018-01-12 08:30
Jup, unfortunately I won't be able to work on this issue until February (am currently working the last two weeks on my current job and need to hand over everything, see https://boastr.net/blog )

Also unfortunately I don't have any promo codes left for the current version of Bettersnaptool and would need to build a non-app-store version, which I also can't do until February.

**Comment by goirle** [comment] 2018-01-12 10:18
Unfortunately you are taking the easy way out here

I payed fore your product so it is your responsibility to make sure that the app is working without any issues. Therefore you can’t hide behind a time issue at your end.

So please let me know what action you will undertake on a short term to resolve this issue.

- Deliver a working app
- or a refund





Op 12 jan. 2018, om 09:30 heeft Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


Jup, unfortunately I won't be able to work on this issue until February (am currently working the last two weeks on my current job and need to hand over everything, see https://boastr.net/blog )

Also unfortunately I don't have any promo codes left for the current version of Bettersnaptool and would need to build a non-app-store version, which I also can't do until February.

**Comment by fifafu** [comment] 2018-01-12 10:33
Refunds are possible within 30days of purchase. (Even after using the 45day trial). You can contact my reseller Fastspring via support@fastspring.com to get a refund.

Of course if you can reproduce the problem reliably I'll immediately be able to fix it. But reproducing a problem that only happens on some machines takes time.

**Comment by nienkeboomsma** [comment] 2018-01-12 10:59
@goirle might I request that you send any further messages regarding your desire for a refund via email? This is an issue tracker, not a place for personal customer support, so your posts are (in my opinion) rather off-topic.

**Comment by fifafu** [comment] 2018-01-13 11:57
One question to everybody, as I'm currently looking into this a bit:
When you are talking about "Window Snapping", do you mean the default Windows-like snapping, which can be enabled in the BetterTouchTool settings? (See screenshot) 
Or are you talking about custom snap areas?  

![image](https://user-images.githubusercontent.com/8820811/34905835-40d2d272-f861-11e7-912c-7e2cca8a7ecf.png)

**Comment by nienkeboomsma** [comment] 2018-01-13 11:59
I'm talking about custom snap areas. I have 'Window Snapping' disabled because I don't want the predetermined functionality as described in that tab, I just want the custom snap areas.

**Comment by tomislav** [comment] 2018-01-13 12:08
Custom snap areas. Mine are set to show on a key press.

**Comment by sunnyskc** [comment] 2018-01-30 07:14
Commented on another similar issue, but this one seems more active, I'm having the same issues with custom snap areas, but regular default snapping stops working as well for me.

**Comment by sunnyskc** [comment] 2018-02-14 02:54
Just to add some more info, whenever snap areas stop working for me, if I move the window normally by clicking and dragging on the titlebar, the areas show up again. Not sure if everyone else is also using the "Move window below cursor if [key] is pressed while you move the cursor".

**Comment by kwb425** [comment] 2018-04-23 15:13
I have the same issue here,
and adding some detail conditions where I could reproduce the issue:
1. custom snap areas 
2. move window below cursor if [key] is pressed while you move the cursor -> enabled
3. when I drag any portion of desktop with no purpose (no app moves), custom snap areas won't show up afterwords, with 2. feature
4. when I drag any app (this time the selected app moves), custom snap areas comes up again, with 2. feature

very similar to @sunnyskc 's 
but trying to give more detailed elaboration :)

**Comment by juanbrena** [comment] 2018-04-25 17:52
I was having this trouble as well. Custom and normal window snapping were not working. After reading this thread and finding no solution I did the following steps:
1. exported my current license, found under the "About" tab in Preferences. 
2. used an App Cleaner to fully remove BTT
3. downloaded BTT again
4. used my exported license to sign BTT
5. snapping and custom snapping work

Now I literally just did this and so I don't know if maybe in the future it'll stopped working again but for now I'm glad it works how it should.

**Comment by KeithGillette** [comment] 2018-05-16 17:51
For the past two weeks I have been experiencing similar failures of custom & normal window snapping with BetterSnapTool 1.8 on my MacBook Pro (with or without 2 external 1080p displays) running MacOS 10.13.4.

**Closed** 2018-11-08 11:45 UTC
