### ISSUE TITLE
Shift, Alt, Ctrl and created F1-12 keys aren't working on touch bar

### ISSUE THREAD

**Issue by agentmith** [folivoraAI/BetterTouchTool#236] opened 2017-01-11 05:23 UTC
**IMPORTANT** : Don't post private requests here (e.g. license issues etc.) please send me an e-mail to boastr.net@gmail.com for such issues.

#### Description of your bug/question/feature request...:

I created a set of F1-12 keys on the touch bar to have them always out as default, since Apple got rid of the option to do that (you can only access the F1-12 keys while pressing Fn, and the keyboard shortcut option doesn't work for most of the applications I've tried). 

The function keys work don't work correctly in combination with shift, alt, etc. It's easiest to test with Alt-F4. I compared to the Apple version of F4 (while holding the Fn key) which works as intended. The BTT version is just hitting the corresponding function key without shift, alt, etc.

**What kind of Mac are you using?**

2016 rMBP 15"  MacOS 10.12.2

**Which input device (e.g. MacBook Trackad, Magic Mouse, Magic Trackpad Touch Bar) is affected by this?**

Touch Bar

**Which versions of macOS and BetterTouchTool are you running?**
1.985 (578)

**Other information:** (e.g. stacktraces, related issues, screenshots,suggestions how to fix, etc)

Let me know what would help and I'll provide it. This is the closest thing I've found to a solution and I'm so close to having it back the way it was.

Note: In case of bugreports, please make sure you have the latest version and already tried to restart your system :-). If you encounter a crash, please attach a crashlog from the macOS Console.app => User Diagnostic Reports

**Comment by DarkFighter** [comment] 2017-04-21 16:47
👍

**Comment by lennartcl** [comment] 2017-10-30 08:58
+1

also, this appears to be a duplicate of https://github.com/fifafu/BetterTouchTool/issues/992

**Comment by norbertstoll** [comment] 2018-10-12 07:57
+1

**Closed** 2018-11-08 11:49 UTC
