### ISSUE TITLE
Haptic Feedback for Multi-Finger Clicks Not Working

### ISSUE THREAD

**Issue by jdlien** [folivoraAI/BetterTouchTool#1558] opened 2017-09-28 13:59 UTC
On macOS High Sierra 10.13.0, the Magic Trackpad 2 does not issue haptic feedback while BetterTouchTool is running. Single finger clicking works normally, but two-finger, three-finger, four-finger, etc clicks and force clicks do not issue haptic feedback so there is no click sensation.

This is true for all stable and alpha versions of BTT (current alpha as of this time is 2.308 (686). The issue immediately goes away when BTT is closed. I have also tried resetting BTT to default settings with no change to this behavior.

This issue can be partially worked around by checking "Do NOT override the system's default two-finger haptic response", which at least allows haptic feedback for
- two-finger clicks (but NOT two-finger force clicks)
- three-finger clicks AND force-clicks

This issue is happening to me on a Hackintosh system but my 2016 MacBook Pro 15" is working normally with a Magic TrackPad 2 and with the built-in trackpad. I'm running the 10.13.1 developer beta 1 on the MacBook Pro, so am unable to confirm if this is due to a bug in 10.13.0 that was fixed in 10.13.1 beta.

**Comment by fifafu** [comment] 2017-09-29 11:59
I just updated to the macOS beta but unfortunately I'm unable to reproduce the issue.
Do you know whether the Hackintosh uses the exact same frameworks as a normal Mac? (Sorry I don't have a lot of experience with current Hackintosh setups)

If possible plrease go to the about tab in BTT and click the "Export Debug Info" button. This will create a folder BetterTouchToolDebug on your Desktop. Please send that to boastr.net@gmail.com (it'll provide me your exact settings, maybe I can then reproduce the issue)

**Comment by fifafu** [comment] 2017-10-01 15:22
Could you check whether your force click settings look like in this screenshot?
![image](https://user-images.githubusercontent.com/8820811/31056093-b1e36184-a6cc-11e7-8dde-a7dad331b8c5.png)

**Comment by jdlien** [comment] 2017-10-01 16:00
My settings look exactly like that - I’m using the defaults, other than that I now have the "Do NOT override" checkbox checked because otherwise I can’t two-finger click or three finger click.

As a workaround to this issue, could you just make that checkbox also affect two-finger FORCE clicks, four finger clicks and four finger force clicks? It already fixes everything else. (Obviously with that on, one loses the more intense click sensation for those kinds of clicks, that’s better than having no click at all!)

**Comment by fifafu** [comment] 2017-10-01 16:08
Unfortunately this only works "good enough" for two finger clicks, for other clicks the systems haptic feedback trigger isn't the same as in BTT. Thus you'd feel the response way before or after the action has triggered which is super confusing.

I vaguely remember a similar issue which happened when the pairing between the Magic Trackpad and the Mac somehow was in a weird state. Have you already tried whether this also happens when the trackpad is connected via USB?

**Comment by jdlien** [comment] 2017-10-01 16:14
I am just testing it now with USB plugged in and I'm afraid it still behaves the same - no feedback.

I also plugged it into my MacBook Pro and it worked okay there with the same version of BTT (but that machine is running 10.13.1 beta).

**Comment by fifafu** [comment] 2017-10-01 16:20
😟 could you check whether changing the feedback type to "New BTT Default Click" changes anything? (that uses a different API to generate the feedback)

![image](https://user-images.githubusercontent.com/8820811/31056645-25f8075c-a6d5-11e7-914d-7cbba06ec256.png)

**Comment by jdlien** [comment] 2017-10-01 16:27
New BTT Default Normal Click does indeed work! So that is interesting.

Also, I just tried this on another user profile on this same Mac, and noticed something interesting: At first launch, all the clicks worked fine with the defaults, then after installing my license key (because apparently this is a per-user setting) I lost the clicks. Why would installing the license have this effect? Is BTT limited in some way prior to license installation?

What's the easiest way to remove the license so that I can test this again?

**Comment by jdlien** [comment] 2017-10-01 16:32
Okay, I found the BetterTouchTool folder in ~/Library/Application Support and deleted it, but that didn't make the clicks start working on that profile. Maybe BTT still hadn't loaded or something when I observed the clicks working - probably a false alarm.

**Comment by fifafu** [comment] 2017-10-01 16:32
That is very weird indeed :-) The license should have no effect at all.

You can test by deleting the file with the .bttlicense file in ~/Library/Application Support/BetterTouchTool

**Comment by fifafu** [comment] 2017-10-01 16:34
This means that everything seems to work as intended, just the (private) API that creates the haptic response doesn't work for some reason. The "New" versions use a slightly less private API to produce the haptic feedback.

**Comment by jdlien** [comment] 2017-10-01 16:42
Okay, another test produced some interesting results. I swore that for a moment after switching to the other profile (charmaine), clicks worked, then they stopped. So went back into my profile (jdlien) and shut down BTT, then started it on the other profile and then everything is working fine.

So... this is starting to make it seem like there's something with my jdlien profile. Apparently settings in one profile are somehow affecting the other.

Another test I did was to log into the other profile, charmaine, with BTT shut down on jdlien. On charmaine, all the clicks worked. I then added a single BTT shortcut which was Cmd+Q on a Four finger FORCE click. After that, the four finger force click did NOT produce feedback but all other clicks did.

I removed the four finger force click shortcut, and haptics still didn't work on the 4-finger force click,but they did again after restarting BTT on charmaine. (It's still shut down on jdlien).

Ugh, sorry for the dump of info - I hope some of this is helpful!

**Comment by fifafu** [comment] 2017-10-01 16:44
BTT only disables the system default response if a gesture that needs to trigger haptic feedback for that specific number of fingers is added to BTT. It then generates the haptic feedback using the private APIs.

**Comment by jdlien** [comment] 2017-10-01 16:47
The weird thing about that is that I definitely don't have a gesture configured for two-finger clicks (I do for two finger force click, though), but it stops two-finger clicks from producing feedback. Does this make sense or is that another mystery?

**Comment by jdlien** [comment] 2017-10-01 16:49
(I also just realized that enabling that checkbox for not overriding two-finger clicks also makes me lose the ability to two-finger force click with BTT).

**Comment by fifafu** [comment] 2017-10-01 16:52
That makes sense as  there is no way to differentiate between force click and normal click, thus BTT needs to disable the feedback completely when a two finger click OR force click is added.

**Comment by gongzhexuan** [comment] 2017-10-03 14:46
I have exactly the same issue as jdlien. Using macOS Sierra 10.13 official version and BTT 2.310, my MacBook Pro (15 inch Mid 2014) does not provide haptic feedback for 3-5 figure click/force clicks. The New BTT Default (Force) Click works but I don't find any way to make the others work. I miss the strong/spring feedback I was using before.

**Comment by fifafu** [comment] 2017-10-03 15:25
Does the live view show that the pressure of the fingers is recognized? Do the bubbles get bigger/darker when pressing harder?

**Comment by jdlien** [comment] 2017-10-03 15:27
It does for me. And the force clicks and stuff *work* but I just don’t get the haptic feedback so I can’t tell the difference between click and force click. The only thing affected is the haptic sensations themselves.

**Comment by fifafu** [comment] 2017-10-03 15:31
Ah ok yes makes sense, otherwise the "new" haptic feedback variants wouldn't work either.

Unfortunately I'm currently out of ideas and as this is all private API there is nobody at Apple I could ask for help ;-( I have had only 3 reports of users that encountered issues with the clicks so far, so this seems to be some super specific issue...

For now you'll have to switch the haptic feedback to the "new" styles. If anybody has any new findings, please post them here.

**Comment by MohammadAG** [comment] 2017-10-04 17:25
FWIW, Magic Trackpad 2 on a iMac 2011 I use also has this issue, but my other Magic Trackpad 2 on a Mac Mini 2014 does not. Both are on 10.13.

**Comment by bulutcy** [comment] 2017-10-04 21:43
I lost haptic feedback on my 3 finger click as well.
My Magic Trackpad 2 on a iMac 2011 has this issue.
My Magic Trackpad 2 on a MacBook Retina 2012 is working fine.

**Comment by fifafu** [comment] 2017-10-04 21:59
Very interesting, so currently we have  two very old imacs, but also one macbook from 2014 and a hackintosh.

Did you update to High Sierra or did you do a fresh install?

**Comment by jdlien** [comment] 2017-10-04 22:02
In my case, I upgraded all my stuff. Both the Hackintosh and the MacBook Pro 2016 which does work.

**Comment by bulutcy** [comment] 2017-10-05 00:14
@fifafu  
Both on High Sierra atm.
2012 iMac clean install, then transferred my data using Time Machine Hdd migration.
2013 Macbook, updated from Sierra.

**Comment by MohammadAG** [comment] 2017-10-09 08:48
Tested this for no reason on my 2017 MBP 15", works fine with the Magic Trackpad 2 (and the internal one).
So to recap:
2014 Mac Mini works.
2017 MacBook Pro works.
2011 iMac does not.

All devices were upgraded to 10.13, the 2011 iMac is technically not supported by the Magic Trackpad 2, but I have a BLE 4.0 dongle attached to it.

**Comment by fifafu** [comment] 2017-10-16 15:18
In the next version of BTT which will be released soon, please try this terminal command (while BTT is quit):
```defaults write com.hegenberg.BetterTouchTool BTTHapticFeedbackOnUnrecognizedDevices YES```

It will force BTT to play the haptic feedback even if the device id doesn't match - I assume this might be the case on hackintoshes or machines with custom BTLE dongles. Not sure whether that'll fix it though.

**Comment by jdlien** [comment] 2017-10-18 23:00
Sigh, I still haven't been able to try this because I broke macOS installation on the Hackintosh by (stupidly) attempting to install an update. Once TonyMacx86 updates unibeast to support High Sierra that should let me get things working again, hopefully and I can try this.

**Comment by gahabana** [comment] 2017-10-21 12:10
https://github.com/fifafu/BetterTouchTool/issues/1643


Hi @fifafu Here is screenshot of Type/Model of mac - it's 2017 MacBook Pro 13" with TouchBar

![image](https://user-images.githubusercontent.com/881265/31851615-a0cba314-b669-11e7-99bd-f76d9c267520.png)

Hope this helps ?

**Comment by gahabana** [comment] 2017-10-22 07:20
@fifafu , 
my issue is not lack of haptic feedback - it is lack of sound/click. As you have closed the other entry (#1664 [https://github.com/fifafu/BetterTouchTool/issues/1643](url) ) i am not sure it is being addressed.
I do get haptic feedback (vibration or feeling of pushing the TrackPad) but i get no sound/click confirmation ... Yes haptic feedback seems to bit lot weaker then before MacOs upgrade to HighSierra but click's are completely missing. 

Should i create a new 'issue' or you think this thread will address it ?
tx!

(btw, i did try removeing BTT completely - deleting ~/Library/Application Support/BetterTouchTool folder etc but it made no difference.

Thank you !!!

**Comment by stormbeta** [comment] 2017-10-25 00:02
I'm having this issue now too after upgrading - nothing special, just the standard internal trackpad on a 2015 13" MBP.

There's some haptic feedback, but it's extremely weak and there's no audible click. I tried the unrecognized device workaround, but it didn't help.

It only affects multi-finger clicks, not single finger.

**Comment by jdlien** [comment] 2017-10-29 16:06
Andreas, I finally got my Hackintosh fixed and had a chance to try this out.
`defaults write com.hegenberg.BetterTouchTool BTTHapticFeedbackOnUnrecognizedDevices YES`
This seems to have fixed my problems! All haptic feedback is now working properly, even without the "Do Not override" checkbox checked.

Let me know if you'd like me to do any more testing.

**Comment by jeppe67** [comment] 2018-01-11 21:34
Same issue here. No haptic feedback on three finger click.

I have tried the terminal command. I have tried the "Do not override..." checkbox. I have tried the "New BTT click". Still doesn't work.

The haptic feedback works fine if I quit BTT.

**Comment by zeroskie** [comment] 2018-04-16 20:35
Hi there. I just recently updated to High Sierra and immediately noticed that I don't have any click of haptic feedback when using 3 finger gestures. The functionality is still there and seems to work, but its driving me a little crazy.

Using a Mac Pro 2013 running macOS 10.13.4. Using Magic Trackpad 2.

The one and two finger haptic feedback seems to work without issue.

I have tried:

Terminal command
New BTT normal click
Uninstalling and reinstalling BTT
I was wondering if anyone has made any headway into this issue?

**Comment by targumanu** [comment] 2018-04-18 14:05
I had been having the same issue, but I was able to restore haptic feedback by changing the default haptic response patterns for normal clicks and force clicks from `BTT Default Normal Click` to `New BTT Default Normal Click` and from `BTT Default ForceClick` to `New BTT Default ForceClick`, respectively:
![screen shot 2018-04-18 at 18 47 12](https://user-images.githubusercontent.com/8336293/38936521-659bb96a-433a-11e8-88d0-7b755f58b8ba.png)

However, changing the haptic response pattern for a specific gesture:
![screen shot 2018-04-18 at 18 48 19](https://user-images.githubusercontent.com/8336293/38936704-d0da5984-433a-11e8-9867-1af0955207a0.png)
to anything but `BTT Default ForceClick` has absolutely no effect, so all force clicks have the same default feedback pattern regardless of their individual settings.

**Comment by zsiegel92** [comment] 2018-04-21 19:32
For me, "New BTT Default Normal Click" and "New BTT Default Force Click" made all haptic feedback occur as indicated. With every other option I tried (and I did try a few more before following this issue), there was NO haptic response for >2-finger input (not for any BTT-configured interactions; only OS X-configured interactions had feedback). I even edited the per-gesture responses, which had no effect whatsoever on haptic feedback.

Certain gestures (such as 4-finger click vs 4-finger force click) absolutely require haptic feedback to be distinguishable/usable.

Perhaps "New BTT Default..." should be the...default...

---on a 2012 MB Air, OS X 10.13.1, lifetime BTT license---

**Comment by fifafu** [comment] 2018-04-22 17:14
Unfortunately I can't make them default because they don't feel as good as the other options and there are only very very few systems affected.

It would be great if I could somehow detect an affected system, but so far there doesn't seem to be a real pattern :-(

**Closed** 2018-11-08 11:46 UTC
