### ISSUE TITLE
3-finger click bug?

### ISSUE THREAD

**Issue by billycastelli** [folivoraAI/BetterTouchTool#710] opened 2017-03-23 21:11 UTC
I have middle click mapped to a 3 finger click. When I lift one finger up (so 2 fingers are on the trackpad now, but no additional pressure applied), another, 2-finger left click is triggered. I do not have a 2 finger click mapped in BTT, so this is the system click being triggered. I am not sure why this happens, not sure if this is a bug or a setting I have overlooked. Any help is appreciated. 

Macbook Pro (2015) Trackpad

#### Device information:

Type of Mac: MacBook Pro
macOS version: 10.12.3
BetterTouchTool version: 2.017 (608)

**Comment by fifafu** [comment] 2017-03-23 21:14
That's weird. Are you maybe using the system's three finger dragging?

**Comment by billycastelli** [comment] 2017-03-23 21:21
I have all 3-finger system gestures turned off.

**Comment by fifafu** [comment] 2017-03-24 10:34
Could you attach an export of your gestures? (using the preset export button in the BTT preferences) 
Alternatively you can send it to boastr.net@gmail.com

**Comment by billycastelli** [comment] 2017-03-24 20:28
I sent them in an e-mail, thanks for your help

**Comment by fifafu** [comment] 2017-03-24 21:15
Very weird, I can't reproduce the issue at all :-(
 Could you try if updating to the latest alpha (2.084)  changes the behavior for you?

**Comment by jastronaut** [comment] 2017-03-24 23:06
I'm pretty sure I have the same issue too, using the same laptop @billycastelli has as well.

**Comment by billycastelli** [comment] 2017-03-24 23:15
Updated to alpha, same behavior. 

Here's a video showing it. 
https://drive.google.com/open?id=0B7J2zxLy0SJ6SnY3b05sRk9iSzA

**Comment by fifafu** [comment] 2017-03-25 10:03
Unfortunately I still can't reproduce this. Maybe it's a specific combination of settings that causes it. Could you also send me the ~/Library/Preferences/com.hegenberg.BetterTouchTool.plist?

Another thing: are you maybe still "clicking" with the other two fingers while removing the third finger? You say "no additional pressure", but do you actually lower the pressure on all three fingers or just on the one you lift?

**Comment by shoegnome** [comment] 2017-03-28 01:16
I'm seeing a similar issue. I set up the 3-finger click to give me the middle mouse click but it's not working. I'm an ARCHICAD user, so pretty much bought BTT for the ability to pan with the trackpad. 3-finger click doesn't even change the cursor, so I can't even get to the point of testing the lift 2 fingers off technique.

Show Live View registers the 3-finger click, but no other app does. 

I was hoping this was just user error being so new to BTT (which is fantastic btw), but sadly I don't think that's the case.

Device information:

Type of Mac: MacBook Pro 15" Late 2016
macOS version: 10.12.3
BetterTouchTool version: 2.084

**Comment by shoegnome** [comment] 2017-03-28 16:00
Did a little more research this morning. 3 finger click works, but not the "use special middleclick mode (for CAD users)". Again, can't tell if this is user error or not.

In my CAD program, double clicking with 3 fingers emulates double clicking with the middle mouse button (in my case zoom extents). But 3 finger click then release 2 fingers does nothing.

**Comment by jedatu** [comment] 2017-03-29 13:56
This may or may not be unrelated, but I have had a rule connected to 3-finger tap which worked fine.  However, a recent update seems to have stopped it from working.  

My 3-finger-tap+cmd gesture was assigned to trigger the "start recording drawing/mouse gesture".  Now if I click the pad with two fingers and slide, BTT starts recording a mouse gesture.    

Also, if I cmd+dbl-tap-3-fingers it seems like the drawing zone is present and invisible.  At that point I can't click on text that is behind that box and I am forced to restart BTT.
-   Model Name:	MacBook Pro
-   Model Identifier:	MacBookPro11,3
-   Processor Name:	Intel Core i7
-   Processor Speed:	2.8 GHz
-   OS Version: 10.12.2 (16C68)

I did recently upgrade to Sierra--maybe it's related.

**Comment by Yakovlev13** [comment] 2017-05-02 12:04
I have similar issue, with right-click assigned to 3 fingers click. I have no idea why, but in Chrome it's working, in Finder almost never. I have to restart BTT than it's working for a while (also in Finder). In Chrome all the time. Even in Live View it can recognizes 3 fingers click, but no gesture it's recognized ( even gesture is assigned to 3 fingers click). 
Of course, 3 fingers click is set in Global settings for trackpad  

MacBook pro 13" 2017 w TouchBar. 
macOS 10.12.4
BTT 2.071

**Comment by aaronpropst** [comment] 2017-07-03 18:25
Same as @jedatu and @Yakovlev13  I had a command+3 finger tap gesture that stopped working consistently in the last couple releases.   I really miss it.

MacBook Pro (Retina, 15-inch, Late 2013)
MacOs: 10.12.5 (16F73)
BTT: 2.261 (651)

**Comment by joshpugh** [comment] 2017-08-29 14:38
Yep I'm having this issue too. In the Live View, it registers as "3 Finger Tap" 100% of the time. However below "3 Finger Tap" it should say "Middle Click" and sometimes instead "Only gestures you have already setup in BTT will be recognized correctly".

This to me says that it's still picking it up as 3 Finger Tap but dismissing it for some reason?

**Comment by GarethBlain** [comment] 2017-11-05 15:58
Okay I'm having what I THINK is a simalar or related issue. I use 3 finger drag and 3 finger click for middle mouse (browsers etc) and I noticed recently (sorry I have no idea when it started!) that when I drag it starts after the mouse has moved a bit and therefore drags the item NOW under the mouse and NOT the item that was under it when I started. SO I have to move it a tiny bit in a direction that won't take the mouse out of the objects drag area THEN drag it around.
To try and fix this issue I turned on the advanced option and the "Three Finger drag optimizastions" AND this fixed the drag issue! YEY!! BUT then I noticed that 3 finger click now didn't work and triggered a single click. :( Turning the optimization off resolved the 3 finger click and brought back the delayed drag... 😢 

Maybe this will help in the identification of the issue... 😬

**Comment by cinges** [comment] 2018-05-09 18:07
Same here, its about the time to find out the problem..:D Im able to run some diagnostic program if you want. I have set 3 finger click as right click. In chrome its working, in Finder almost never. I must do three finger at chrome several times and then its working for some time in finder..

**Closed** 2018-11-08 11:49 UTC
Labels: Need other people who can reproduce the issue
