### ISSUE TITLE
Radial Menu

### ISSUE THREAD

**Issue by DCNielsen** [folivoraAI/BetterTouchTool#1100] opened 2017-06-20 15:45 UTC
**IMPORTANT:** Don't post private requests here (e.g. license issues, etc.). Please send me an email at boastr.net@gmail.com instead.

---

#### Feature Request:
I'd LOVE to see a radial menu option. I'm a Wacom user and I have a lot of modifier click actions mapped from BTT through the "Normal Mice" triggers. Wacom's built in Radial Menu requires me to commit an entire button and all possible button modifiers just to a single radial menu if I want one. The trade-off isn't worth it for me because I lose lots of immediate modifier + click commands to get 9 (slower) click and drag triggered actions. 

I'd love to have a radial available as one of those modifier clicks though. I would prefer to keep a middle click or right click, but if I use a modifier, get a specific Radial. That way I can do almost any action with only my pen and some modifiers. The gestures you've made for BTT are cool, but what would be a lot more useful for myself and other digital artists is something that allowed straight lines. This is true because the shortest distance between two points is a line and not whatever curved thing I can draw as a gesture. HOWEVER - Rather than bother finding a way to capture straight lines for Gestures, a Radial Menu accomplishes this same purpose and includes valuable UI feedback. 

Functionally, I would hold down a button that reveals a Radial under my mouse position, move up/down or left/right or diagonal to make a choice, release the button and the action runs. Additionally vs. a curved-line gesture I'm more assured to end up closer to my starting position and ready to paint where I started.

This could be triggered by anything and not just mouse clicks.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
All

#### Device information:

Type of Mac: Laptop
macOS version: 10.11.6
BetterTouchTool version: 2.21

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

See RadialMenu for AutoHotkey (best implementation, in my opinion!) or Wacom Radial for implementation examples. Thanks for all your hard work on BTT! Great program.

---

**Note:** Before bug reporting, please make sure you have the latest version of BetterTouchTool and that you have already tried to restart your system :-). If you encounter a crash, please attach a crash log from the macOS Console.app from the "User Diagnostic Reports" section.

**Comment by DCNielsen** [comment] 2017-06-20 15:55
For clarity's sake, I'm saying a Right Click by itself should be able to act just like a Right Click. An fn+Right Click and drag should be able to trigger a Radial menu. When released it should run be able to run a command under the mouse which is either A. neutral/middle position or N. Arrayed around the mouse location when the Fn+ Right click and drag started.

**Comment by SynerG** [comment] 2017-09-28 11:03
I would love to see a Radial Menu feature in BTT.
Currently, I have a Wacom tablet connected to my Mac just for this functionality, as I don't typically use the pen.

For reference, in Wacom you assign a built-in key to show a Radial Menu at cursor position. The Radial Menu shows 8 different actions around the cursor, each one in a different angle, but all easily accessible from the cursor. Each action may be final (e.g. open an app, press keyboard shortcut) or may invoke a different Radial Menu.
It can be seen, for example, in this [video](https://www.youtube.com/watch?v=w61PeTcjWkc)

This way you don't need to remember a lot of shortcuts, but easily choose it visually (of course, if you use it often, you learn to automatize it) and being able to invoke other radial menus/submenus the possibilities are endless. 

But to use this feature, you need to have a Wacom tablet and, as @DCNielsen said, commit an ExpressKey to invoke the Radial Menu. Plus, the set of Actions in Wacom is not as powerful as using BTT.

I would much prefer to have a Radial Menu feature inside BTT. 

As I see it, there would be a new type of Action to "Show Radial Menu". This action could be triggered in any of the regular ways (e.g. gesture, shortcut). And each option shown in the Radial Menu would trigger a new Action.
The interaction model proposed by @DCNielsen by pressing and holding a key is also a possibility beyond regular triggering methods (e.g. gesture, shortcut).

It would be necessary a window to manage the list of Radial Menus that you have defined and which options are shown in each one.

**Comment by andyconlin** [comment] 2018-05-17 00:02
I didn't know of radial menus before coming across this thread, but had an idea for something similar when I heard of the [HTML overlay feature](https://docs.bettertouchtool.net/docs/floating_html_menu.html) when it was released.  By chance, have either of you (@DCNielsen or @SynerG) built an HTML overlay to act as a radial menu?  If not, [this demo](https://codepen.io/web-tiki/pen/ZYmZoV) (via [this answer](https://stackoverflow.com/a/29231413/8550628)) could be a good starting point for building such a menu (also [this pie menu generator](http://pmg.softwaretailoring.net/)).

If one of us ends up building a generic menu, we could make a BTT radial menu generator ([à la Chris Lennon's crypto widget generator](https://chrislennon.github.io/Crypto-Touchbar-App/)).

Radial menus may still be useful as a fully-supported feature/action (to eliminate the the need to code the overlay), but I definitely like the customizability that the HTML overlay provides.

When my [non-radial] overlay is at a decent completion point, I'll share it here in case others want to iterate on it.

**Comment by DCNielsen** [comment] 2018-05-17 20:56
Hi Andy! 
Yes, I love the new HTML menu-under-mouse function. I wish I was a little quicker on the draw with HTML/CSS. It takes me longer than I like to work stuff out, even though it's rather simple. I've used @fifafu 's example to play around with a radial. It goes about 90% of the way to what I asked for here while also opening us up to whatever we can pull off with HTML. 

These other links that you shared are helpful as well.

What I really want now is the ability to bring up one of these HTML overlays with a mouse button and simple directional drag rather than the more complex gestures (that take too much flourishing as shortcuts IMO). That piece would make BTT's almost as good as what I had going with AutoHotkey and RadialMenu. With that pairing on PC, I could: 1) Directional drag, 2) bring up a menu while still holding mouse/pen down. 3) release the button on my choice and it would trigger.

That way I could do every common action in a complex app like Photoshop super-fast by barely touching the keyboard.

Thanks for all your work on BTT lately Andreas. Great additions.

**Comment by fifafu** [comment] 2018-05-17 21:14
have you had a look at the drawing gestures? their weak spot are straight lines, but they should work good enough if you don't define too many of them.

They would allow to show the menu with a simple mouse gesture.

**Comment by DCNielsen** [comment] 2018-05-17 21:18
I tried it but it seemed a little unreliable to get them to trigger. This was awhile back time though. I will try again. Do you think an "onmouseup" trigger could work in the HTML to do the lift up part of what I'm after? I can give it a go.

**Comment by DCNielsen** [comment] 2018-05-17 21:38
What I'm actually trying to ask is, can the HTML overlay see that the mouse still down after I trigger it from BTT? Do I need a new click to have a mouseup event?

**Comment by DCNielsen** [comment] 2018-05-17 21:49
As far as the gesture triggering, it's close! Looks like I can get away with 3 of the cardinal directions before its interpreting a "Right" gesture as an "Up".  Though what I'm really after is all 4 and the 4 diagonal 45° ones (down left, etc). Also, sequenced ones (L shape, etc.. Up+Right) don't hurt anything but again, those are straight-line gestures. If I could do this, I could scrap jitouch which I use for these. In the meantime, I might be able to trigger BTT actions via Applescript through jitouch and use jitouch for straight line recognition? Going to play around.

**Comment by andyconlin** [comment] 2018-05-20 22:38
I'm glad to see the shared enthusiasm for the HTML overlay possibilities!

@DCNielsen, in addition to "onmouseup" did you try ["onmouseover"](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onmouseover)?  It might need to be set to a target area within the radial menu item, rather than the whole thing, so that you could scroll across multiple items without accidentally triggering them until intended.  

Also, I just had an idea for the first half of resetting mouse position.  The thought was to have the HTML overlay save the mouse position when it loads and then return the mouse to origin before closing.  Perhaps immediately simulating a mouse event and capturing the x & y coordinates _(it could just use the center point if you always launch the menu with enough space to rely on it launching with the mouse at center, as HTML overlay doesn't open with mouse at center point if there isn't enough space at screen edges)_.  Then, right before calling the BTT trigger, it could return the mouse to the start point before the HTML overlay closes.  _The problem is_, I can't find a way to move the mouse with javascript (it may not be currently possible).

I'm neither an advanced web designer nor an experienced mac developer—I simply dabble in both, so I don't know if the above will work or if the next suggestion is an efficient, fast, or responsible methodology; maybe @fifafu could advise on the potential performance.

The suggestion: whatever triggers the HTML overlay could first have a sub-action (probably shell script?) that writes the current mouse position to a self-made [plist](https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/PropertyLists/AboutPropertyLists/AboutPropertyLists.html) before launching the HTML overlay.  Then, all BTT actions that are triggered by the radial menu have a sub-action that first gets the previous coordinates from the plist and moves the mouse there before executing the rest of the action.

Without extensive experience in MacOS development, I don't know what good options there are for temporary data caching, or if plist read/write is fast enough.  If there's something better (or even if plist is sufficient), and if it's not very user-friendly, this would make for a great feature request—some sort of key:value properties service (temporary and/or persistent) within BTT so that actions could save and re-access data between executions and between different actions.  I'll do some more research and perhaps post the [feature request](https://community.folivora.ai/c/feature-requests).  In the meantime, I'm going to experiment with using plists as quick data exchange.

Please forgive my rambling, stream of consciousness comment.  If nothing else, it facilitated my brainstorming process :)

**Closed** 2018-11-08 11:47 UTC
