### ISSUE TITLE
BTT preventing MacBook sleep, Alertsounds when lid closed. (should be silent in standby)

### ISSUE THREAD

**Issue by RonaldRegister** [folivoraAI/BetterTouchTool#1792] opened 2017-11-26 10:06 UTC
#### Description of bug/feature request/question:

MacBook Pro 2014 sleep issue on High Sierra. When charging and closing the lid, after a few seconds several alertsounds. See system.log MacBook does not sleep. Clean install of High Sierra did not fix this problem.

#### Device information:

Type of Mac: MacBook pro Retina 2014 13"
macOS version: High Sierra 10.13.1
BetterTouchTool version: Latest stable (was this 2.291?) And now also on Alpha 2.316

#### Additional information (e.g. StackTraces, related issues, screenshots, workarounds, etc.):

Nov 25 11:57:34 Ts-MacBook-Pro com.apple.xpc.launchd[1] (com.hegenberg.BTTRelaunch.7260[416]): Service exited due to signal: Terminated: 15 sent by BetterTouchTool[426]
Nov 25 11:57:36 Ts-MacBook-Pro BetterTouchTool[426]: assertion failed: 17B48: libxpc.dylib + 73297 [58676E88-35FD-3CF3-99BB-2A82E09F8058]: 0x89

**Comment by fifafu** [comment] 2017-11-26 10:15
Hey,

That message shows that BTT restarts after waking from sleep. However it's probably not the cause for waking up. (So far everytime this was reported it wasn't BTT but something else)

Maybe check if you have any external hardware that may cause auch wakeups/prevent sleep.

**Comment by RonaldRegister** [comment] 2017-11-26 10:28
I’ve done very extensive research, no other hardware or software connected or active. There is not a wake-up/powersave setting I haven’t tried. Disabling BTT immediately solves the problem.

Exactly at the time the alertsounds are audible with the lid closed, the is the only thing visible in console.

The message appears WHILE the display is closed. Disabling BTT instantly fixes the issue. The issue never appeared in Sierra. Only after upgrading to high Sierra

On 26 Nov 2017, at 11:15, Andreas Hegenberg <notifications@github.com> wrote:

Hey,

That message shows that BTT restarts after waking from sleep. However it's probably not the cause for waking up. (So far everytime this was reported it wasn't BTT but something else)

Maybe check if you have any external hardware that may cause auch wakeups/prevent sleep.

**Comment by fifafu** [comment] 2017-11-26 10:35
Do you maybe have a trigger in the other section in BetterTouchTool  for "before mac goes to sleep"?

**Comment by RonaldRegister** [comment] 2017-11-26 11:06
Nope. Only 1 keyboard shortcut, and 2 trackpad gestures.

**Comment by fifafu** [comment] 2017-11-26 11:27
Very weird. Maybe there is something in the logs - could you go to the about tab in BetterTouchTool and click the "export debug info" button? (if possible first reproduce the problem).
This will create a folder called BetterTouchToolDebug on your Desktop, it'd be great if you could send that to me (boastr.net@gmail.com)

**Comment by RonaldRegister** [comment] 2017-11-26 11:39
Ofcourse, just emailed it.

**Comment by fifafu** [comment] 2017-11-26 13:36
Unfortunately that all looks normal :-( 

Does your mac sleep correctly if you use the apple menubar item?

**Comment by RonaldRegister** [comment] 2017-11-26 15:23
Will try ASAP and report back.

**Comment by RonaldRegister** [comment] 2017-11-27 08:42
I've done some testing and it looks like it, when I use the sleep menu item (instead of closing the lid) the issue does not happen. 

Very weird, can't wrap my head around it.

**Comment by ovidiur** [comment] 2017-11-27 21:16
I have the same problem, it's been driving me crazy. I've been able to pinpoint it to BetterTouchTool by closing all other apps one by one until only BTT is left. 
The symptoms are exactly as RonaldRegister described. My system.log shows a lot of instances of this message:

`Nov 27 23:06:05 sanitarium-mb BetterTouchTool[5911]: assertion failed: 17B48: libxpc.dylib + 73297 [58676E88-35FD-3CF3-99BB-2A82E09F8058]: 0x89`

My machine is a 13 inch mid 2014 MacBook Pro. I've sent you the debug dump over email.

**Comment by fifafu** [comment] 2017-11-27 21:25
Oh that's very interesting. You both seem to have this message.

I'll ask Apple what it means. (BTT uses XPC services to execute Apple Scripts in the background e.g. for the Touch Bar)

**Comment by RonaldRegister** [comment] 2017-11-28 13:34
First of all, thank you for the support. It's always nice to see when softwaredevelopers really help and try to resolve rare issues.

Second, let me know if there is more I can do to debug or test.

**Comment by RonaldRegister** [comment] 2017-12-02 14:31
Strange that there aren't more people reacting. We can't be the only ones.

Any info from Apple?

**Comment by RonaldRegister** [comment] 2017-12-18 09:25
Any progress?

**Comment by paulmarrington** [comment] 2018-01-17 01:29
You aren't the only two. It is just a problem that is not easy to track down. I only noticed it when BTT action on wake didn't work. I assumed it was just BTT, not an interaction problem. If I use "sleep" on the Apple menu then wake, all is OK.

**Comment by RonaldRegister** [comment] 2018-06-05 09:52
Any progress?

**Comment by orosoiu** [comment] 2018-06-06 09:59
I think @fifafu gave up on this one. I don't believe it will ever be addressed. I had to stop using BTT because of this issue, and replace it with a different app.

**Comment by RonaldRegister** [comment] 2018-06-25 08:34
aah, that's to bad!

What app are you using instead? 

I wish i could use the native Apple keyboard shortcuts. It's proven once again that third party tools are not 100% working, unfortunately

**Closed** 2018-11-08 11:45 UTC
