### ISSUE TITLE
Gesture are not triggering 3/5 of the time

### ISSUE THREAD

**Issue by Tazintosh** [folivoraAI/BetterTouchTool#1045] opened 2017-06-05 07:59 UTC
Hi folks,

#### Description of bug/feature request/question:
Since the last update (2.20 641), my unique gesture fail to trigger most of the time.
The gesture is 5 Fingers Click, which triggers ⌘W
Since (yes) I'm using BTT for years and get a license just for this gesture, it not a lack of habit. I've instantly noticed the behavior changed.

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
I'm using a Magic Trackpad (v1).

#### Device information:
Type of Mac: Mac Pro early 2008
macOS version: El Capitan
BetterTouchTool version: 2.20 (641)

Thanks in advance for your time and support.

**Comment by hvedemelsbof** [comment] 2017-06-06 08:31
Funny, i have the same problem with ⌘W, just with a different gesture, the threefinger middle tap

**Comment by Nyappy** [comment] 2017-06-06 08:40
I have the same problem.
in 3 Fingers double tap ,triggers ⌘W.
90% succeeded, 10% fail.

MacBook Pro late 2016/trackpad
BTT Ver.2.20(641)

**Comment by Tazintosh** [comment] 2017-06-06 10:09
Today, I've fully cleaned + reinstalled BTT from ma Mac.
Issue is still there.
BTW, my statistics since this topic, is much more about 80% fail, 20% success.
Later I counted, I had to make the gesture 17 times before it triggers! BTT has no use anymore for me since it kill my productivity. For the moment, I'm trying to go back to manual ⌘W :(

**Comment by Nyappy** [comment] 2017-06-06 10:27
And 3 Finger double tap is recognized in 4 Finger double tap. 2/10 times.
4 Finger double tap is recognized in "two times 4 Finger double tap" 3/10 times.
It is not usable.

**Comment by fifafu** [comment] 2017-06-06 14:04
Mhh this all seems to be working fine here :-(

Could you try if disabling thumb handling in the advanced trackpad settings fixes your issues?

**Comment by fifafu** [comment] 2017-06-06 14:06
For now you can also downgrade in case this doesn't help : https://boastr.net/releases

**Comment by Tazintosh** [comment] 2017-06-06 14:13
Filtering the thumb/palm instantly fixed the issue!
Thanks.

**Comment by ps3rules** [comment] 2017-06-07 11:36
I downgraded down to version 2.13 to eliminate the fail to trigger problem.All other versions above 2.13 have the same trigger problem.

**Comment by hvedemelsbof** [comment] 2017-06-07 12:02
Solved by disabling thumb-correction here

**Comment by hvedemelsbof** [comment] 2017-06-07 12:04
Thanks for a nice app btw, Andreas

**Comment by Nyappy** [comment] 2017-06-08 06:53
"disabling thumb handling" is no effective.

"roll back to 2.10" and "two times 4 Finger double tap" is cleared.
"in 3 Fingers double tap ,triggers ⌘W" is got better. 95% successed,5% failed.
Almost good.

Thank you for your help,anyway.
I hope the cause will become apparent.
BTT is a very important item for me :)

**Comment by fifafu** [comment] 2018-02-03 09:04
I'm currently closing some older issues, in case this still doesn't work correctly, please comment again or open a new issue.

I'll have much more time moving forward as I'm now self-employed. Please excuse not being able to solve/reply to this earlier.

**Comment by ps3rules** [comment] 2018-02-03 09:24
It still doesn't work correctly on mac os high sierra 10.13.3 version 2.332(713).And we no longer have the ability to roll back.

**Comment by fifafu** [comment] 2018-02-03 09:39
If you still encounter this please go to the about tab in BTT and click the "Export debug information" button. This will create a folder called "BetterTouchToolDebug" on your desktop. If possible please send that to boastr.net@gmail.com

**Comment by fifafu** [comment] 2018-02-04 17:03
One note: if you are using three finger dragging, make sure to enable the three finger drag optimizations in the BTT preferences and restart BTT afterwards:

![image](https://user-images.githubusercontent.com/8820811/35779980-a7c10884-09d5-11e8-99a3-10f8ecc73725.png)

**Comment by ps3rules** [comment] 2018-02-04 17:08
Here is my setup.


On 4 Feb 2018, at 19:03, Andreas Hegenberg <notifications@github.com<mailto:notifications@github.com>> wrote:


One note: if you are using three finger dragging, make sure to enable the three finger drag optimizations in the BTT preferences and restart BTT afterwards:

[image]<https://user-images.githubusercontent.com/8820811/35779980-a7c10884-09d5-11e8-99a3-10f8ecc73725.png>

**Closed** 2018-11-08 11:47 UTC
