### ISSUE TITLE
Execute Shell Script Executing multiple times w/ Touchbar widget

### ISSUE THREAD

**Issue by Lugoues** [folivoraAI/BetterTouchTool#2429] opened 2018-04-10 16:40 UTC
A custom widget using "Execute Shell Script / Task" as the action executes twice per `' (keydown/keyup maybe?). Is there a way to prevent this or is it a bug?

#### Affected input device (e.g. MacBook Trackpad, Magic Mouse/Trackpad, Touch Bar, etc.):
Touch Bar Widget + Execute Shell Script / Task

#### Device information:
Type of Mac: MacBook Pro 2017
macOS version:  10.12.6
BetterTouchTool version: 2.422

**Comment by xcrzx** [comment] 2018-04-18 11:25
Same issue. TouchBar widget with "Run Apple Script" action runs the script twice on touch.

**Comment by xcrzx** [comment] 2018-05-08 08:13
Any updates on this issue? It's really annoying.

**Comment by fifafu** [comment] 2018-05-08 08:17
Unfortunately I'm unable to reproduce this.
In case it is caused by touching too long & triggering a repeat, have you tried to adjust the repeat rate?

![image](https://user-images.githubusercontent.com/8820811/39745914-0c76196a-52a9-11e8-997b-7d3a63f2f7c9.png)

**Comment by xcrzx** [comment] 2018-05-09 10:34
It doesn't seem to be related to long press. No matter how long I touch the button, the action always triggered twice. I've tried to adjust repeat rate but it doesn't help. 

I use following configuration for the widget:
```
{
  "BTTWidgetName" : "Test",
  "BTTTriggerType" : 642,
  "BTTTriggerTypeDescription" : "Shell Script \/ Task Widget",
  "BTTTriggerClass" : "BTTTriggerTypeTouchBar",
  "BTTPredefinedActionType" : 172,
  "BTTPredefinedActionName" : "Run Apple Script (enter directly as text)",
  "BTTInlineAppleScript" : "tell application \"iTerm\"\r\ttell current window\r\t\tset newTab to (create tab with default profile)\r\t\ttell current session of newTab\r\t\t\twrite text \"echo Test\"\r\t\tend tell\r\tend tell\rend tell",
  "BTTShellScriptWidgetGestureConfig" : "\/bin\/bash:::-c",
  "BTTAdditionalConfiguration" : "\/bin\/bash:::-c",
  "BTTEnabled" : 1,
  "BTTOrder" : 11,
  "BTTTriggerConfig" : {
    "BTTTouchBarItemIconHeight" : 22,
    "BTTTouchBarItemIconWidth" : 22,
    "BTTTouchBarItemPadding" : 0,
    "BTTTouchBarFreeSpaceAfterButton" : "5.000000",
    "BTTTouchBarButtonColor" : "75.323769, 75.323769, 75.323769, 255.000000",
    "BTTTouchBarAlwaysShowButton" : "0",
    "BTTTouchBarShellScriptString" : "echo Test",
    "BTTTouchBarAlternateBackgroundColor" : "75.323769, 75.323769, 75.323769, 255.000000",
    "BTTTouchBarScriptUpdateInterval" : 30
  }
}
```
 On touch it always creates two new iTerm tabs.

**Comment by fifafu** [comment] 2018-05-09 10:45
Ha thanks, that helped!
Should be fixed in a few minutes with the next update.

**Comment by fifafu** [comment] 2018-05-09 11:15
Would be great if you could test with version 2.500

**Comment by xcrzx** [comment] 2018-05-09 12:33
Yup, it's fixed, thank you!

**Closed** 2018-05-11 14:10 UTC
