### ISSUE TITLE
Issue: Dropbox API request authorization

### ISSUE THREAD

**Issue by itsskin** [folivoraAI/BetterTouchTool#1174] opened 2017-07-05 05:09 UTC
Hi! BTT 2.265 is opening a browser page with Dropbox API request authorization every time computer is switched on or awaken from the sleep. Clicking Allow does not change anything. Accessibility is Privacy controls is enabled.

MacOS 10.12.5

Thank you

**Comment by folkrav** [comment] 2017-07-06 14:24
Can confirm, same behavior on my work computer. Same BTT version, OS X 10.11.5.

**Comment by Raziel480** [comment] 2017-07-08 16:36
Same issue here. BTT 2.266 and 10.12.5

**Comment by itsskin** [comment] 2017-07-15 06:33
2.267 is still doing the same

**Comment by fifafu** [comment] 2017-07-15 06:55
Is there any special network setup on your Macs? (Corporate proxies or the like?

**Comment by itsskin** [comment] 2017-07-15 07:09
No, nothing special...

**Comment by folkrav** [comment] 2017-07-17 14:36
Nothing special either. Straight DHCP through our network switch.

**Comment by folkrav** [comment] 2017-07-19 19:15
Is it fixed in an upcoming release? Both issues were closed on the same day, despite saying in #1130 that it will be tracked in this one.

**Comment by fifafu** [comment] 2017-07-19 19:16
This one is still open. I'll try to reproduce it soon.

**Comment by folkrav** [comment] 2017-07-20 14:24
Oh, sorry, somehow checked the status twice on 1130. If there is anything I can provide (logs?), I'll be happy to.

**Comment by itsskin** [comment] 2017-07-27 15:01
Please look at this issue. Clothing unnecessary tabs after every wake-up/btt launch is big PITA :D

**Comment by fifafu** [comment] 2017-09-22 22:22
Are you still seeing this? I have recently added the latest Dropbox SDK

**Comment by itsskin** [comment] 2017-09-25 12:58
I moved to a new computer, but while in transition I did see it on the old one. Seem if you click "don't allow the page to create an alerts any more" (or something like it :) ) breaks the workflow. On new computer I did let Chrome to open a dopbox app and it was never an issue again.

**Comment by Worie** [comment] 2017-11-19 14:44
For me it still occurs. Perhaps because I use Safari as my default browser, but no matter what option I pick. One mac is running BTT 2.313, macOS 10.13.1, the other one 10.12.6 - same BTT. They both act the same way (ask after each wake up from sleep)

**Comment by ChasKane** [comment] 2018-08-31 21:54
I'm still having this too. Quite annoying XD

MacOS 10.13.6
BTT v2.608

**Comment by jamonntoast** [comment] 2018-09-20 09:32
Same here    MacOS 10.13.6 | BTT v2.608

Been having this issue since middle 2017, yes.. 2017.

**Closed** 2018-11-08 11:47 UTC

**Comment by jeffnuss** [comment] 2019-01-18 22:31
I see this issue got closed. However, I'm still seeing this on v2.697 (1002) on macOS 10.14.2. It's not every single time I awake from sleep, but has happened as often as a few times a day.
